version: "3"
services:
  alpine:
    build:
      context: ./alpine
      dockerfile: Dockerfile
  windows:
    build:
      context: ./windows
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
